version: "3.9"

services:
    redis:
        image: redis
        
    frontend:
        image: frontend
        ports:
            - 5000:5000

    backend:
        image: backend
        environment:
            - REDIS_HOST=redis
        ports:
            - 8080:8080