version: "3.8"

services:
    redis:
        image: redis
        
    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=example     
        
    frontend:
        image: frontend
        ports:
            - 5000:5000
            
    backend:
        image: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=example
        ports:
            - 8080:8080
        depends_on:
            - db