version: "3.8"

services:
    reversed_proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
           - NGINX_PORT=80
        ports:
            - "80:80"
        depends_on:
            - backend
            - frontend
        
    redis:
        image: redis
        
    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=example
        volumes:
            - ./database:/var/lib/postgresql/data
        
    frontend:
        image: frontend
            
    backend:
        image: backend
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=example
        depends_on:
            - db
            - redis