version: "3.8"

services:
    reversed_proxy:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        environment:
           - NGINX_PORT=80
        ports:
            - "3000:80"
        depends_on:
            - backend
            - frontend
        
    redis:
        image: redis
        
    db:
        image: postgres:latest
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=example
        volumes:
            - ./database:/var/lib/postgresql/data
        
    frontend:
        image: frontend
        ports:
            - "5000:5000"
        environment:
            - REACT_APP_BACKEND_URL=http://localhost:3000
            
    backend:
        image: backend
        ports:
            - "8080:8080"
        environment:
            - REDIS_HOST=redis
            - POSTGRES_HOST=db
            - POSTGRES_PASSWORD=example
            - REQUEST_ORIGIN=http://localhost:3000
        depends_on:
            - db
            - redis