version: '3.8'

services:
    web-service:
        image: devopsdockeruh/simple-web-service
        expose:
            - "8080"
        ports:
            - "8080:8080"
        command:
            - server
        container_name: web-service